CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;


DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210102122701_Initial') THEN
    CREATE TABLE "WeatherForecasts" (
        "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        "Date" timestamp without time zone NOT NULL,
        "TemperatureC" integer NOT NULL,
        "Summary" text NULL,
        CONSTRAINT "PK_WeatherForecasts" PRIMARY KEY ("Id")
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210102122701_Initial') THEN
    INSERT INTO "WeatherForecasts" ("Id", "Date", "Summary", "TemperatureC")
    VALUES (-1, TIMESTAMP '2020-01-01 00:00:00', 'Nice', 25);
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210102122701_Initial') THEN
    SELECT setval(
        pg_get_serial_sequence('"WeatherForecasts"', 'Id'),
        GREATEST(
            (SELECT MAX("Id") FROM "WeatherForecasts") + 1,
            nextval(pg_get_serial_sequence('"WeatherForecasts"', 'Id'))),
        false);
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20210102122701_Initial') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20210102122701_Initial', '5.0.1');
    END IF;
END $$;
COMMIT;

